'use client';

import { useState } from 'react';
import { NeoCard } from '@/components/ui/NeoCard';

interface FAQItem {
  question: string;
  answer: string;
  category: 'privacy' | 'borrower' | 'lender' | 'technical';
}

export default function HelpPage() {
  const [activeCategory, setActiveCategory] = useState<string>('all');
  const [expandedId, setExpandedId] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: 'What is KiyanLend?',
      answer: 'KiyanLend is a privacy-preserving micro-lending platform that connects borrowers with lenders using encrypted AI assessments. Borrowers can access capital without exposing their raw financial data, while lenders make informed decisions based on AI-generated Trust Scores.',
      category: 'privacy',
    },
    {
      question: 'How does my data stay private?',
      answer: 'All your financial documents are stored in your personal SecretVault using end-to-end encryption. When a lender requests an assessment, a pre-trained nilAI model runs on your encrypted data using secure multi-party computation. The model never decrypts your files and only outputs a Trust Score (1-100) and a short Risk Assessment summary.',
      category: 'privacy',
    },
    {
      question: 'What can lenders see about me?',
      answer: 'Lenders can only see: your display name, country (optional), loan request details (amount, duration, purpose), number of connected wallets, and your Trust Score if an assessment has been completed. They cannot see your raw financial documents, specific transaction amounts, account balances, or any personally identifiable information beyond what you choose to display.',
      category: 'privacy',
    },
    {
      question: 'Can I revoke lender access to my data?',
      answer: 'Yes, absolutely. You can disable assessment permissions at any time from your Profile page. This prevents new lenders from requesting assessments. Already-completed assessments remain visible to those lenders, but no new processing can occur on your encrypted data.',
      category: 'privacy',
    },
    {
      question: 'How do I create a loan request?',
      answer: 'Go to your Borrower Dashboard, scroll to "Create Loan Request," fill in the amount, duration, purpose, and optional note. Make sure you\'ve uploaded documents to your SecretVault and connected at least one wallet. You can also toggle whether to allow lenders to request private assessments.',
      category: 'borrower',
    },
    {
      question: 'What documents should I upload?',
      answer: 'Upload any documents that show your financial stability: mobile money statements, bank statements, utility bills, income proof (pay stubs, invoices), or other relevant financial records. More comprehensive data typically results in more accurate Trust Scores.',
      category: 'borrower',
    },
    {
      question: 'Why connect multiple wallets?',
      answer: 'Connecting multiple wallets demonstrates ownership of diverse assets and builds trust with lenders. Your primary wallet is displayed on your borrower profile. You can manage all connected wallets from your Profile page.',
      category: 'borrower',
    },
    {
      question: 'What is a Trust Score?',
      answer: 'A Trust Score is a number from 1 to 100 that represents your creditworthiness based on AI analysis of your encrypted financial data. It\'s computed by pre-trained nilAI models that analyze payment history, income patterns, debt ratios, and savings behavior—all without decrypting your files.',
      category: 'borrower',
    },
    {
      question: 'How do I request an assessment?',
      answer: 'Browse borrowers in the Lender Marketplace, apply filters to find matches, and click "Request Assessment" on any borrower card. You\'ll see the fee (typically 0.5 credits), confirm privacy terms, and submit. If the borrower has enabled assessments, processing begins immediately. Otherwise, you\'ll wait for their consent.',
      category: 'lender',
    },
    {
      question: 'What is the assessment fee?',
      answer: 'The assessment fee (typically 0.5 credits) covers the computational cost of running the AI model on encrypted data. This fee is non-refundable once processing begins. You can purchase credits from your Profile page.',
      category: 'lender',
    },
    {
      question: 'How long does an assessment take?',
      answer: 'Most assessments complete within 2-5 minutes. Processing time depends on the amount of encrypted data and current system load. You\'ll receive a notification when the Trust Score and Risk Assessment are ready.',
      category: 'lender',
    },
    {
      question: 'What is a Risk Assessment?',
      answer: 'A Risk Assessment is a 3-5 bullet point summary generated by the AI model alongside the Trust Score. It highlights key factors like payment history, income stability, debt ratios, and savings patterns—all derived from encrypted data without exposing raw details.',
      category: 'lender',
    },
    {
      question: 'What is nilAI?',
      answer: 'nilAI is the encrypted AI framework that powers our Trust Score assessments. It uses secure multi-party computation to run machine learning models on encrypted data. The model processes your financial information without ever decrypting it, ensuring complete privacy.',
      category: 'technical',
    },
    {
      question: 'What is a SecretVault?',
      answer: 'SecretVault is your personal encrypted storage for financial documents. Files uploaded to your SecretVault are encrypted end-to-end and can only be processed by authorized nilAI models. No human—including lenders and platform admins—can view your raw files.',
      category: 'technical',
    },
    {
      question: 'Is my data stored on-chain?',
      answer: 'Your encrypted documents are stored off-chain in your SecretVault. Only wallet addresses, loan requests, and assessment results (Trust Scores) may be recorded on-chain for transparency and auditability. Raw financial data never touches the blockchain.',
      category: 'technical',
    },
  ];

  const categories = [
    { id: 'all', label: 'All Topics', color: 'bg-primary' },
    { id: 'privacy', label: 'Privacy & Security', color: 'bg-success' },
    { id: 'borrower', label: 'For Borrowers', color: 'bg-secondary' },
    { id: 'lender', label: 'For Lenders', color: 'bg-accent' },
    { id: 'technical', label: 'Technical', color: 'bg-danger' },
  ];

  const filteredFaqs = activeCategory === 'all'
    ? faqs
    : faqs.filter(faq => faq.category === activeCategory);

  return (
    <main className="min-h-screen py-8">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-4xl sm:text-5xl font-black uppercase mb-4">Help & Privacy</h1>
          <p className="text-xl font-semibold">
            Everything you need to know about private micro-lending
          </p>
        </div>

        <NeoCard bg="bg-primary" className="mb-8">
          <div className="text-center">
            <h2 className="text-2xl font-black uppercase mb-4">Privacy First</h2>
            <p className="text-lg font-semibold max-w-2xl mx-auto">
              Your financial data stays encrypted. Lenders never see raw documents. Only AI-powered Trust Scores are shared. You control who can request assessments.
            </p>
          </div>
        </NeoCard>

        <div className="mb-8">
          <p className="font-bold text-sm uppercase tracking-wide mb-4">Browse by Category</p>
          <div className="flex flex-wrap gap-3">
            {categories.map(cat => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={`neo-button px-4 py-2 ${cat.color} ${
                  activeCategory === cat.id ? 'opacity-100' : 'opacity-60'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-4 mb-12">
          {filteredFaqs.map((faq, idx) => (
            <NeoCard key={idx} bg="bg-white">
              <button
                onClick={() => setExpandedId(expandedId === idx ? null : idx)}
                className="w-full text-left"
              >
                <div className="flex items-start justify-between gap-4">
                  <h3 className="text-lg font-black">{faq.question}</h3>
                  <svg
                    className={`w-6 h-6 flex-shrink-0 transition-transform ${
                      expandedId === idx ? 'rotate-180' : ''
                    }`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </button>
              {expandedId === idx && (
                <div className="mt-4 pt-4 border-t-4 border-foreground">
                  <p className="text-sm font-semibold leading-relaxed">{faq.answer}</p>
                </div>
              )}
            </NeoCard>
          ))}
        </div>

        <NeoCard bg="bg-secondary">
          <div className="text-center">
            <h2 className="text-2xl font-black uppercase mb-4">Still Have Questions?</h2>
            <p className="text-lg font-semibold mb-6">
              Our support team is here to help you understand how privacy-preserving lending works.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="neo-button bg-foreground text-background px-6 py-3">
                Contact Support
              </button>
              <button className="neo-button bg-accent px-6 py-3">
                Join Community
              </button>
            </div>
          </div>
        </NeoCard>

        <div className="mt-12 grid md:grid-cols-3 gap-6">
          <NeoCard bg="bg-accent">
            <div className="text-center">
              <svg className="w-12 h-12 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              <h4 className="font-black text-lg mb-2">Encrypted Storage</h4>
              <p className="text-sm font-semibold">
                All documents in SecretVault are encrypted end-to-end
              </p>
            </div>
          </NeoCard>

          <NeoCard bg="bg-success">
            <div className="text-center">
              <svg className="w-12 h-12 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
              <h4 className="font-black text-lg mb-2">Private AI</h4>
              <p className="text-sm font-semibold">
                Models run on encrypted data without decryption
              </p>
            </div>
          </NeoCard>

          <NeoCard bg="bg-primary">
            <div className="text-center">
              <svg className="w-12 h-12 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
              </svg>
              <h4 className="font-black text-lg mb-2">You Control Access</h4>
              <p className="text-sm font-semibold">
                Enable or disable assessments anytime from Profile
              </p>
            </div>
          </NeoCard>
        </div>
      </div>
    </main>
  );
}
